# Generated by Django 2.0.9 on 2019-05-05 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('diary', '0001_squashed_0007_auto_20180803_2122'), ('diary', '0008_auto_20180803_2123'), ('diary', '0009_auto_20180830_2224'), ('diary', '0010_auto_20180830_2227'), ('diary', '0011_auto_20180918_2038'), ('diary', '0012_auto_20180923_1755'), ('diary', '0013_auto_20180923_1811'), ('diary', '0014_auto_20180924_2116'), ('diary', '0015_auto_20180926_2153'), ('diary', '0016_auto_20181224_0121'), ('diary', '0017_auto_20190108_2039'), ('diary', '0018_auto_20190204_2147'), ('diary', '0019_auto_20190416_2145'), ('diary', '0020_auto_20190424_1603')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('job_status', models.CharField(choices=[('non', 'none / undefined'), ('pen', 'pending'), ('run', 'running'), ('fin', 'finished'), ('nor', 'normal termination'), ('err', 'error termination'), ('oth', 'other termination'), ('obs', 'obsolete')], max_length=3)),
                ('main_name', models.CharField(max_length=200)),
                ('sub_dir', models.CharField(editable=False, max_length=500)),
                ('job_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('info', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.CharField(blank=True, max_length=10, null=True)),
                ('sub_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('analysis_status', models.CharField(choices=[('opn', 'open'), ('ong', 'ongoing'), ('don', 'done')], default='opn', max_length=3)),
                ('base_runs', models.ManyToManyField(blank=True, to='diary.Job')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('logfile_path', models.CharField(blank=True, editable=False, max_length=200)),
                ('readme_filename', models.CharField(blank=True, editable=False, max_length=200)),
                ('result_assessment', models.CharField(blank=True, choices=[('ok', 'ok'), ('nok', 'not ok'), ('oth', 'other'), ('isu', 'issue')], max_length=3)),
                ('result_summary', models.TextField(blank=True)),
                ('solver', models.CharField(blank=True, editable=False, max_length=10)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
