# Generated by Django 2.0.9 on 2019-05-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_squashed_0020_auto_20190424_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='keyword_string',
            field=models.TextField(blank=True),
        ),
    ]
