# Generated by Django 2.0.9 on 2019-05-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_add_keywords_to_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('non', 'none / undefined'), ('pen', 'pending'), ('run', 'running'), ('fin', 'finished'), ('nor', 'normal termination'), ('err', 'error termination'), ('oth', 'other termination')], max_length=3),
        ),
        migrations.AlterField(
            model_name='job',
            name='result_assessment',
            field=models.CharField(blank=True, choices=[('ok', 'ok'), ('nok', 'not ok'), ('oth', 'other'), ('isu', 'issue'), ('obs', 'obsolete')], max_length=3),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
